### ISSUE TITLE
Remove "forked from jetwell/adfc-radschulwegplan-frontend" line in github

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-radschulwegplan-frontend#16]
See:

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by jetwell** [comment]
I've deleted the jetwell/adfc-radschulwegplan-frontend project. The tabacha/adfc-radschulwegplan-frontend project must also be deleted.

**Comment by tabacha** [comment]
done
